version: '3.3'

volumes:
  postgres_data:
  static:
  media:

services:
  db:
    image: postgres:14.0
    volumes:
     - postgres_data:/var/lib/postgresql/14/main
    env_file:
      - ./.env
    networks:
      - app-network
  web:
    build: .
    restart: always
    ports:
     - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
    networks:
      - app-network
  nginx:
    image: nginx:1.19.3
    ports:
     - "9200:9200"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app/app/static:/var/html/static/
      - ./media:/var/html/media/
    depends_on:
      - web
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
